name: lms
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  dio: ^5.1.1
  form_builder_validators: ^8.5.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.10
  flutter_widget_from_html: ^0.10.0
  image_picker: ^0.8.7+2
  cloud_firestore: ^4.5.0
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
